// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequestForOwner = `-- name: GetRequestForOwner :one
SELECT
    r.id,
    r.project_id,
    r.virtual_key_id,
    r.provider_credential_id,
    r.provider,
    r.model,
    r.is_stream,
    r.status,
    r.started_at,
    r.first_chunk_at,
    r.completed_at,
    r.latency_ms,
    r.ttft_ms,
    r.upstream_http_status,
    r.error_category,
    r.retry_count,
    r.prompt_tokens,
    r.completion_tokens,
    r.total_tokens,
    r.usage_source,
    r.pricing_id,
    r.estimated_cost_nano_usd,
    r.upstream_request_id,
    r.trace_id,
    r.created_at,
    p.name AS project_name,
    k.key_prefix AS virtual_key_prefix
FROM gateway_requests AS r
JOIN projects AS p
  ON p.id = r.project_id
 AND p.owner_user_id = $1
JOIN virtual_api_keys AS k
  ON k.id = r.virtual_key_id
WHERE r.id = $2
`

type GetRequestForOwnerParams struct {
	OwnerUserID pgtype.UUID
	ID          pgtype.UUID
}

type GetRequestForOwnerRow struct {
	ID                   pgtype.UUID
	ProjectID            pgtype.UUID
	VirtualKeyID         pgtype.UUID
	ProviderCredentialID pgtype.UUID
	Provider             string
	Model                string
	IsStream             bool
	Status               string
	StartedAt            pgtype.Timestamptz
	FirstChunkAt         pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
	LatencyMs            pgtype.Int8
	TtftMs               pgtype.Int8
	UpstreamHttpStatus   pgtype.Int4
	ErrorCategory        pgtype.Text
	RetryCount           int16
	PromptTokens         pgtype.Int8
	CompletionTokens     pgtype.Int8
	TotalTokens          pgtype.Int8
	UsageSource          pgtype.Text
	PricingID            pgtype.UUID
	EstimatedCostNanoUsd pgtype.Int8
	UpstreamRequestID    pgtype.Text
	TraceID              pgtype.Text
	CreatedAt            pgtype.Timestamptz
	ProjectName          string
	VirtualKeyPrefix     string
}

func (q *Queries) GetRequestForOwner(ctx context.Context, arg GetRequestForOwnerParams) (GetRequestForOwnerRow, error) {
	row := q.db.QueryRow(ctx, getRequestForOwner, arg.OwnerUserID, arg.ID)
	var i GetRequestForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.VirtualKeyID,
		&i.ProviderCredentialID,
		&i.Provider,
		&i.Model,
		&i.IsStream,
		&i.Status,
		&i.StartedAt,
		&i.FirstChunkAt,
		&i.CompletedAt,
		&i.LatencyMs,
		&i.TtftMs,
		&i.UpstreamHttpStatus,
		&i.ErrorCategory,
		&i.RetryCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.UsageSource,
		&i.PricingID,
		&i.EstimatedCostNanoUsd,
		&i.UpstreamRequestID,
		&i.TraceID,
		&i.CreatedAt,
		&i.ProjectName,
		&i.VirtualKeyPrefix,
	)
	return i, err
}

const listRequestsForOwner = `-- name: ListRequestsForOwner :many

SELECT
    r.id,
    r.project_id,
    r.virtual_key_id,
    r.provider_credential_id,
    r.provider,
    r.model,
    r.is_stream,
    r.status,
    r.started_at,
    r.first_chunk_at,
    r.completed_at,
    r.latency_ms,
    r.ttft_ms,
    r.upstream_http_status,
    r.error_category,
    r.retry_count,
    r.prompt_tokens,
    r.completion_tokens,
    r.total_tokens,
    r.usage_source,
    r.pricing_id,
    r.estimated_cost_nano_usd,
    r.upstream_request_id,
    r.trace_id,
    r.created_at,
    p.name AS project_name,
    k.key_prefix AS virtual_key_prefix
FROM gateway_requests AS r
JOIN projects AS p
  ON p.id = r.project_id
 AND p.owner_user_id = $1
JOIN virtual_api_keys AS k
  ON k.id = r.virtual_key_id
WHERE ($2::uuid IS NULL OR r.project_id = $2::uuid)
  AND ($3::text IS NULL OR r.provider = $3::text)
  AND ($4::text IS NULL OR r.model = $4::text)
  AND ($5::text IS NULL OR r.status = $5::text)
  AND ($6::boolean IS NULL OR r.is_stream = $6::boolean)
  AND ($7::timestamptz IS NULL OR r.started_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR r.started_at < $8::timestamptz)
  AND (
      $9::timestamptz IS NULL
      OR r.started_at < $9::timestamptz
      OR (r.started_at = $9::timestamptz AND r.id < $10::uuid)
  )
ORDER BY r.started_at DESC, r.id DESC
LIMIT $11
`

type ListRequestsForOwnerParams struct {
	OwnerUserID     pgtype.UUID
	ProjectID       pgtype.UUID
	Provider        pgtype.Text
	Model           pgtype.Text
	Status          pgtype.Text
	IsStream        pgtype.Bool
	From            pgtype.Timestamptz
	To              pgtype.Timestamptz
	CursorStartedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	Limit           int32
}

type ListRequestsForOwnerRow struct {
	ID                   pgtype.UUID
	ProjectID            pgtype.UUID
	VirtualKeyID         pgtype.UUID
	ProviderCredentialID pgtype.UUID
	Provider             string
	Model                string
	IsStream             bool
	Status               string
	StartedAt            pgtype.Timestamptz
	FirstChunkAt         pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
	LatencyMs            pgtype.Int8
	TtftMs               pgtype.Int8
	UpstreamHttpStatus   pgtype.Int4
	ErrorCategory        pgtype.Text
	RetryCount           int16
	PromptTokens         pgtype.Int8
	CompletionTokens     pgtype.Int8
	TotalTokens          pgtype.Int8
	UsageSource          pgtype.Text
	PricingID            pgtype.UUID
	EstimatedCostNanoUsd pgtype.Int8
	UpstreamRequestID    pgtype.Text
	TraceID              pgtype.Text
	CreatedAt            pgtype.Timestamptz
	ProjectName          string
	VirtualKeyPrefix     string
}

// Control Plane analytics queries (Week 7).
//
// Every query is ownership-scoped: the caller supplies owner_user_id and rows
// are joined through projects.owner_user_id. A browser-supplied project_id is
// a filter selector, never proof of access.
//
// Time semantics: [from, to) half-open intervals, UTC. Timeseries buckets use
// generate_series aligned to date_trunc(bucket, from); the first and last
// buckets may be partial. Zero-fill is server-side via LEFT JOIN + COALESCE.
//
// estimated_cost_nano_usd aggregates only base-rate attributed costs (rows
// with a recorded cost). Requests whose usage or price version was unknown
// contribute to counts but not to the cost/token sums.
func (q *Queries) ListRequestsForOwner(ctx context.Context, arg ListRequestsForOwnerParams) ([]ListRequestsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listRequestsForOwner,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.Provider,
		arg.Model,
		arg.Status,
		arg.IsStream,
		arg.From,
		arg.To,
		arg.CursorStartedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsForOwnerRow{}
	for rows.Next() {
		var i ListRequestsForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.VirtualKeyID,
			&i.ProviderCredentialID,
			&i.Provider,
			&i.Model,
			&i.IsStream,
			&i.Status,
			&i.StartedAt,
			&i.FirstChunkAt,
			&i.CompletedAt,
			&i.LatencyMs,
			&i.TtftMs,
			&i.UpstreamHttpStatus,
			&i.ErrorCategory,
			&i.RetryCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.UsageSource,
			&i.PricingID,
			&i.EstimatedCostNanoUsd,
			&i.UpstreamRequestID,
			&i.TraceID,
			&i.CreatedAt,
			&i.ProjectName,
			&i.VirtualKeyPrefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageBreakdownByKeyForOwner = `-- name: UsageBreakdownByKeyForOwner :many
SELECT
    r.virtual_key_id AS key_id,
    k.key_prefix AS key_prefix,
    count(*)::bigint AS requests_total,
    count(*) FILTER (WHERE r.status = 'failed')::bigint AS requests_failed,
    COALESCE(SUM(r.prompt_tokens), 0)::bigint AS prompt_tokens,
    COALESCE(SUM(r.completion_tokens), 0)::bigint AS completion_tokens,
    COALESCE(SUM(r.total_tokens), 0)::bigint AS total_tokens,
    COALESCE(SUM(r.estimated_cost_nano_usd), 0)::bigint AS estimated_cost_nano_usd
FROM gateway_requests AS r
JOIN projects AS p
  ON p.id = r.project_id
 AND p.owner_user_id = $1
JOIN virtual_api_keys AS k
  ON k.id = r.virtual_key_id
WHERE r.started_at >= $2::timestamptz
  AND r.started_at < $3::timestamptz
  AND ($4::uuid IS NULL OR r.project_id = $4::uuid)
GROUP BY r.virtual_key_id, k.key_prefix
ORDER BY COALESCE(SUM(r.estimated_cost_nano_usd), 0) DESC
LIMIT $5
`

type UsageBreakdownByKeyForOwnerParams struct {
	OwnerUserID pgtype.UUID
	From        pgtype.Timestamptz
	To          pgtype.Timestamptz
	ProjectID   pgtype.UUID
	Limit       int32
}

type UsageBreakdownByKeyForOwnerRow struct {
	KeyID                pgtype.UUID
	KeyPrefix            string
	RequestsTotal        int64
	RequestsFailed       int64
	PromptTokens         int64
	CompletionTokens     int64
	TotalTokens          int64
	EstimatedCostNanoUsd int64
}

func (q *Queries) UsageBreakdownByKeyForOwner(ctx context.Context, arg UsageBreakdownByKeyForOwnerParams) ([]UsageBreakdownByKeyForOwnerRow, error) {
	rows, err := q.db.Query(ctx, usageBreakdownByKeyForOwner,
		arg.OwnerUserID,
		arg.From,
		arg.To,
		arg.ProjectID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageBreakdownByKeyForOwnerRow{}
	for rows.Next() {
		var i UsageBreakdownByKeyForOwnerRow
		if err := rows.Scan(
			&i.KeyID,
			&i.KeyPrefix,
			&i.RequestsTotal,
			&i.RequestsFailed,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.EstimatedCostNanoUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageBreakdownByModelForOwner = `-- name: UsageBreakdownByModelForOwner :many
SELECT
    r.model AS key,
    count(*)::bigint AS requests_total,
    count(*) FILTER (WHERE r.status = 'failed')::bigint AS requests_failed,
    COALESCE(SUM(r.prompt_tokens), 0)::bigint AS prompt_tokens,
    COALESCE(SUM(r.completion_tokens), 0)::bigint AS completion_tokens,
    COALESCE(SUM(r.total_tokens), 0)::bigint AS total_tokens,
    COALESCE(SUM(r.estimated_cost_nano_usd), 0)::bigint AS estimated_cost_nano_usd
FROM gateway_requests AS r
JOIN projects AS p
  ON p.id = r.project_id
 AND p.owner_user_id = $1
WHERE r.started_at >= $2::timestamptz
  AND r.started_at < $3::timestamptz
  AND ($4::uuid IS NULL OR r.project_id = $4::uuid)
GROUP BY r.model
ORDER BY COALESCE(SUM(r.estimated_cost_nano_usd), 0) DESC
LIMIT $5
`

type UsageBreakdownByModelForOwnerParams struct {
	OwnerUserID pgtype.UUID
	From        pgtype.Timestamptz
	To          pgtype.Timestamptz
	ProjectID   pgtype.UUID
	Limit       int32
}

type UsageBreakdownByModelForOwnerRow struct {
	Key                  string
	RequestsTotal        int64
	RequestsFailed       int64
	PromptTokens         int64
	CompletionTokens     int64
	TotalTokens          int64
	EstimatedCostNanoUsd int64
}

func (q *Queries) UsageBreakdownByModelForOwner(ctx context.Context, arg UsageBreakdownByModelForOwnerParams) ([]UsageBreakdownByModelForOwnerRow, error) {
	rows, err := q.db.Query(ctx, usageBreakdownByModelForOwner,
		arg.OwnerUserID,
		arg.From,
		arg.To,
		arg.ProjectID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageBreakdownByModelForOwnerRow{}
	for rows.Next() {
		var i UsageBreakdownByModelForOwnerRow
		if err := rows.Scan(
			&i.Key,
			&i.RequestsTotal,
			&i.RequestsFailed,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.EstimatedCostNanoUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageBreakdownByProviderForOwner = `-- name: UsageBreakdownByProviderForOwner :many
SELECT
    r.provider AS key,
    count(*)::bigint AS requests_total,
    count(*) FILTER (WHERE r.status = 'failed')::bigint AS requests_failed,
    COALESCE(SUM(r.prompt_tokens), 0)::bigint AS prompt_tokens,
    COALESCE(SUM(r.completion_tokens), 0)::bigint AS completion_tokens,
    COALESCE(SUM(r.total_tokens), 0)::bigint AS total_tokens,
    COALESCE(SUM(r.estimated_cost_nano_usd), 0)::bigint AS estimated_cost_nano_usd
FROM gateway_requests AS r
JOIN projects AS p
  ON p.id = r.project_id
 AND p.owner_user_id = $1
WHERE r.started_at >= $2::timestamptz
  AND r.started_at < $3::timestamptz
  AND ($4::uuid IS NULL OR r.project_id = $4::uuid)
GROUP BY r.provider
ORDER BY COALESCE(SUM(r.estimated_cost_nano_usd), 0) DESC
LIMIT $5
`

type UsageBreakdownByProviderForOwnerParams struct {
	OwnerUserID pgtype.UUID
	From        pgtype.Timestamptz
	To          pgtype.Timestamptz
	ProjectID   pgtype.UUID
	Limit       int32
}

type UsageBreakdownByProviderForOwnerRow struct {
	Key                  string
	RequestsTotal        int64
	RequestsFailed       int64
	PromptTokens         int64
	CompletionTokens     int64
	TotalTokens          int64
	EstimatedCostNanoUsd int64
}

func (q *Queries) UsageBreakdownByProviderForOwner(ctx context.Context, arg UsageBreakdownByProviderForOwnerParams) ([]UsageBreakdownByProviderForOwnerRow, error) {
	rows, err := q.db.Query(ctx, usageBreakdownByProviderForOwner,
		arg.OwnerUserID,
		arg.From,
		arg.To,
		arg.ProjectID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageBreakdownByProviderForOwnerRow{}
	for rows.Next() {
		var i UsageBreakdownByProviderForOwnerRow
		if err := rows.Scan(
			&i.Key,
			&i.RequestsTotal,
			&i.RequestsFailed,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.EstimatedCostNanoUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageSummaryForOwner = `-- name: UsageSummaryForOwner :one
SELECT
    count(*)::bigint AS requests_total,
    count(*) FILTER (WHERE r.status = 'succeeded')::bigint AS requests_succeeded,
    count(*) FILTER (WHERE r.status = 'failed')::bigint AS requests_failed,
    count(*) FILTER (
        WHERE r.status = 'succeeded'
          AND r.pricing_id IS NOT NULL
          AND r.estimated_cost_nano_usd IS NOT NULL
    )::bigint AS priced_requests,
    COALESCE(SUM(r.prompt_tokens), 0)::bigint AS prompt_tokens,
    COALESCE(SUM(r.completion_tokens), 0)::bigint AS completion_tokens,
    COALESCE(SUM(r.total_tokens), 0)::bigint AS total_tokens,
    COALESCE(SUM(r.estimated_cost_nano_usd), 0)::bigint AS estimated_cost_nano_usd,
    COALESCE(SUM(r.latency_ms), 0)::bigint AS latency_ms_sum,
    count(r.latency_ms)::bigint AS latency_ms_count,
    COALESCE(SUM(r.ttft_ms), 0)::bigint AS ttft_ms_sum,
    count(r.ttft_ms)::bigint AS ttft_ms_count
FROM gateway_requests AS r
JOIN projects AS p
  ON p.id = r.project_id
 AND p.owner_user_id = $1
WHERE r.started_at >= $2::timestamptz
  AND r.started_at < $3::timestamptz
  AND ($4::uuid IS NULL OR r.project_id = $4::uuid)
`

type UsageSummaryForOwnerParams struct {
	OwnerUserID pgtype.UUID
	From        pgtype.Timestamptz
	To          pgtype.Timestamptz
	ProjectID   pgtype.UUID
}

type UsageSummaryForOwnerRow struct {
	RequestsTotal        int64
	RequestsSucceeded    int64
	RequestsFailed       int64
	PricedRequests       int64
	PromptTokens         int64
	CompletionTokens     int64
	TotalTokens          int64
	EstimatedCostNanoUsd int64
	LatencyMsSum         int64
	LatencyMsCount       int64
	TtftMsSum            int64
	TtftMsCount          int64
}

func (q *Queries) UsageSummaryForOwner(ctx context.Context, arg UsageSummaryForOwnerParams) (UsageSummaryForOwnerRow, error) {
	row := q.db.QueryRow(ctx, usageSummaryForOwner,
		arg.OwnerUserID,
		arg.From,
		arg.To,
		arg.ProjectID,
	)
	var i UsageSummaryForOwnerRow
	err := row.Scan(
		&i.RequestsTotal,
		&i.RequestsSucceeded,
		&i.RequestsFailed,
		&i.PricedRequests,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.EstimatedCostNanoUsd,
		&i.LatencyMsSum,
		&i.LatencyMsCount,
		&i.TtftMsSum,
		&i.TtftMsCount,
	)
	return i, err
}

const usageTimeseriesForOwnerDay = `-- name: UsageTimeseriesForOwnerDay :many
SELECT
    buckets.ts::timestamptz AS ts,
    COALESCE(a.requests_total, 0)::bigint AS requests_total,
    COALESCE(a.requests_succeeded, 0)::bigint AS requests_succeeded,
    COALESCE(a.requests_failed, 0)::bigint AS requests_failed,
    COALESCE(a.prompt_tokens, 0)::bigint AS prompt_tokens,
    COALESCE(a.completion_tokens, 0)::bigint AS completion_tokens,
    COALESCE(a.total_tokens, 0)::bigint AS total_tokens,
    COALESCE(a.estimated_cost_nano_usd, 0)::bigint AS estimated_cost_nano_usd
FROM generate_series(
    date_trunc('day', $1::timestamptz),
    date_trunc('day', $2::timestamptz - interval '1 microsecond'),
    interval '1 day'
) AS buckets(ts)
LEFT JOIN (
    SELECT
        date_trunc('day', r.started_at)::timestamptz AS ts,
        count(*)::bigint AS requests_total,
        count(*) FILTER (WHERE r.status = 'succeeded')::bigint AS requests_succeeded,
        count(*) FILTER (WHERE r.status = 'failed')::bigint AS requests_failed,
        COALESCE(SUM(r.prompt_tokens), 0)::bigint AS prompt_tokens,
        COALESCE(SUM(r.completion_tokens), 0)::bigint AS completion_tokens,
        COALESCE(SUM(r.total_tokens), 0)::bigint AS total_tokens,
        COALESCE(SUM(r.estimated_cost_nano_usd), 0)::bigint AS estimated_cost_nano_usd
    FROM gateway_requests AS r
    JOIN projects AS p
      ON p.id = r.project_id
     AND p.owner_user_id = $3
    WHERE r.started_at >= $1::timestamptz
      AND r.started_at < $2::timestamptz
      AND ($4::uuid IS NULL OR r.project_id = $4::uuid)
    GROUP BY 1
) AS a ON a.ts = buckets.ts
ORDER BY buckets.ts ASC
`

type UsageTimeseriesForOwnerDayParams struct {
	From        pgtype.Timestamptz
	To          pgtype.Timestamptz
	OwnerUserID pgtype.UUID
	ProjectID   pgtype.UUID
}

type UsageTimeseriesForOwnerDayRow struct {
	Ts                   pgtype.Timestamptz
	RequestsTotal        int64
	RequestsSucceeded    int64
	RequestsFailed       int64
	PromptTokens         int64
	CompletionTokens     int64
	TotalTokens          int64
	EstimatedCostNanoUsd int64
}

func (q *Queries) UsageTimeseriesForOwnerDay(ctx context.Context, arg UsageTimeseriesForOwnerDayParams) ([]UsageTimeseriesForOwnerDayRow, error) {
	rows, err := q.db.Query(ctx, usageTimeseriesForOwnerDay,
		arg.From,
		arg.To,
		arg.OwnerUserID,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageTimeseriesForOwnerDayRow{}
	for rows.Next() {
		var i UsageTimeseriesForOwnerDayRow
		if err := rows.Scan(
			&i.Ts,
			&i.RequestsTotal,
			&i.RequestsSucceeded,
			&i.RequestsFailed,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.EstimatedCostNanoUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageTimeseriesForOwnerHour = `-- name: UsageTimeseriesForOwnerHour :many
SELECT
    buckets.ts::timestamptz AS ts,
    COALESCE(a.requests_total, 0)::bigint AS requests_total,
    COALESCE(a.requests_succeeded, 0)::bigint AS requests_succeeded,
    COALESCE(a.requests_failed, 0)::bigint AS requests_failed,
    COALESCE(a.prompt_tokens, 0)::bigint AS prompt_tokens,
    COALESCE(a.completion_tokens, 0)::bigint AS completion_tokens,
    COALESCE(a.total_tokens, 0)::bigint AS total_tokens,
    COALESCE(a.estimated_cost_nano_usd, 0)::bigint AS estimated_cost_nano_usd
FROM generate_series(
    date_trunc('hour', $1::timestamptz),
    date_trunc('hour', $2::timestamptz - interval '1 microsecond'),
    interval '1 hour'
) AS buckets(ts)
LEFT JOIN (
    SELECT
        date_trunc('hour', r.started_at)::timestamptz AS ts,
        count(*)::bigint AS requests_total,
        count(*) FILTER (WHERE r.status = 'succeeded')::bigint AS requests_succeeded,
        count(*) FILTER (WHERE r.status = 'failed')::bigint AS requests_failed,
        COALESCE(SUM(r.prompt_tokens), 0)::bigint AS prompt_tokens,
        COALESCE(SUM(r.completion_tokens), 0)::bigint AS completion_tokens,
        COALESCE(SUM(r.total_tokens), 0)::bigint AS total_tokens,
        COALESCE(SUM(r.estimated_cost_nano_usd), 0)::bigint AS estimated_cost_nano_usd
    FROM gateway_requests AS r
    JOIN projects AS p
      ON p.id = r.project_id
     AND p.owner_user_id = $3
    WHERE r.started_at >= $1::timestamptz
      AND r.started_at < $2::timestamptz
      AND ($4::uuid IS NULL OR r.project_id = $4::uuid)
    GROUP BY 1
) AS a ON a.ts = buckets.ts
ORDER BY buckets.ts ASC
`

type UsageTimeseriesForOwnerHourParams struct {
	From        pgtype.Timestamptz
	To          pgtype.Timestamptz
	OwnerUserID pgtype.UUID
	ProjectID   pgtype.UUID
}

type UsageTimeseriesForOwnerHourRow struct {
	Ts                   pgtype.Timestamptz
	RequestsTotal        int64
	RequestsSucceeded    int64
	RequestsFailed       int64
	PromptTokens         int64
	CompletionTokens     int64
	TotalTokens          int64
	EstimatedCostNanoUsd int64
}

func (q *Queries) UsageTimeseriesForOwnerHour(ctx context.Context, arg UsageTimeseriesForOwnerHourParams) ([]UsageTimeseriesForOwnerHourRow, error) {
	rows, err := q.db.Query(ctx, usageTimeseriesForOwnerHour,
		arg.From,
		arg.To,
		arg.OwnerUserID,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageTimeseriesForOwnerHourRow{}
	for rows.Next() {
		var i UsageTimeseriesForOwnerHourRow
		if err := rows.Scan(
			&i.Ts,
			&i.RequestsTotal,
			&i.RequestsSucceeded,
			&i.RequestsFailed,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.EstimatedCostNanoUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
