// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: data_plane.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateVirtualAPIKey = `-- name: AuthenticateVirtualAPIKey :one
SELECT
    keys.id,
    keys.project_id,
    keys.key_prefix
FROM virtual_api_keys AS keys
JOIN projects
  ON projects.id = keys.project_id
WHERE keys.key_prefix = $1
  AND keys.key_hash = $2
  AND keys.status = 'active'
  AND projects.status = 'active'
`

type AuthenticateVirtualAPIKeyParams struct {
	KeyPrefix string
	KeyHash   []byte
}

type AuthenticateVirtualAPIKeyRow struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	KeyPrefix string
}

func (q *Queries) AuthenticateVirtualAPIKey(ctx context.Context, arg AuthenticateVirtualAPIKeyParams) (AuthenticateVirtualAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, authenticateVirtualAPIKey, arg.KeyPrefix, arg.KeyHash)
	var i AuthenticateVirtualAPIKeyRow
	err := row.Scan(&i.ID, &i.ProjectID, &i.KeyPrefix)
	return i, err
}

const createGatewayRequest = `-- name: CreateGatewayRequest :one
INSERT INTO gateway_requests (
    id,
    project_id,
    virtual_key_id,
    provider_credential_id,
    provider,
    model,
    is_stream,
    status,
    started_at,
    trace_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    'in_progress',
    $8,
    $9
)
RETURNING id, project_id, virtual_key_id, provider_credential_id, provider, model, is_stream, status, started_at, created_at
`

type CreateGatewayRequestParams struct {
	ID                   pgtype.UUID
	ProjectID            pgtype.UUID
	VirtualKeyID         pgtype.UUID
	ProviderCredentialID pgtype.UUID
	Provider             string
	Model                string
	IsStream             bool
	StartedAt            pgtype.Timestamptz
	TraceID              pgtype.Text
}

type CreateGatewayRequestRow struct {
	ID                   pgtype.UUID
	ProjectID            pgtype.UUID
	VirtualKeyID         pgtype.UUID
	ProviderCredentialID pgtype.UUID
	Provider             string
	Model                string
	IsStream             bool
	Status               string
	StartedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) CreateGatewayRequest(ctx context.Context, arg CreateGatewayRequestParams) (CreateGatewayRequestRow, error) {
	row := q.db.QueryRow(ctx, createGatewayRequest,
		arg.ID,
		arg.ProjectID,
		arg.VirtualKeyID,
		arg.ProviderCredentialID,
		arg.Provider,
		arg.Model,
		arg.IsStream,
		arg.StartedAt,
		arg.TraceID,
	)
	var i CreateGatewayRequestRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.VirtualKeyID,
		&i.ProviderCredentialID,
		&i.Provider,
		&i.Model,
		&i.IsStream,
		&i.Status,
		&i.StartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const finalizeGatewayRequest = `-- name: FinalizeGatewayRequest :one
UPDATE gateway_requests
SET
    status = $1,
    first_chunk_at = $2,
    completed_at = $3,
    latency_ms = $4,
    ttft_ms = $5,
    upstream_http_status = $6,
    error_category = $7,
    retry_count = $8,
    prompt_tokens = $9,
    completion_tokens = $10,
    total_tokens = $11,
    usage_source = $12,
    pricing_id = $13,
    estimated_cost_nano_usd = $14,
    upstream_request_id = $15
WHERE id = $16
RETURNING
    id,
    project_id,
    virtual_key_id,
    provider_credential_id,
    provider,
    model,
    is_stream,
    status,
    started_at,
    first_chunk_at,
    completed_at,
    latency_ms,
    ttft_ms,
    upstream_http_status,
    error_category,
    retry_count,
    prompt_tokens,
    completion_tokens,
    total_tokens,
    usage_source,
    pricing_id,
    estimated_cost_nano_usd,
    upstream_request_id,
    trace_id,
    created_at
`

type FinalizeGatewayRequestParams struct {
	Status               string
	FirstChunkAt         pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
	LatencyMs            pgtype.Int8
	TtftMs               pgtype.Int8
	UpstreamHttpStatus   pgtype.Int4
	ErrorCategory        pgtype.Text
	RetryCount           int16
	PromptTokens         pgtype.Int8
	CompletionTokens     pgtype.Int8
	TotalTokens          pgtype.Int8
	UsageSource          pgtype.Text
	PricingID            pgtype.UUID
	EstimatedCostNanoUsd pgtype.Int8
	UpstreamRequestID    pgtype.Text
	ID                   pgtype.UUID
}

func (q *Queries) FinalizeGatewayRequest(ctx context.Context, arg FinalizeGatewayRequestParams) (GatewayRequest, error) {
	row := q.db.QueryRow(ctx, finalizeGatewayRequest,
		arg.Status,
		arg.FirstChunkAt,
		arg.CompletedAt,
		arg.LatencyMs,
		arg.TtftMs,
		arg.UpstreamHttpStatus,
		arg.ErrorCategory,
		arg.RetryCount,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.UsageSource,
		arg.PricingID,
		arg.EstimatedCostNanoUsd,
		arg.UpstreamRequestID,
		arg.ID,
	)
	var i GatewayRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.VirtualKeyID,
		&i.ProviderCredentialID,
		&i.Provider,
		&i.Model,
		&i.IsStream,
		&i.Status,
		&i.StartedAt,
		&i.FirstChunkAt,
		&i.CompletedAt,
		&i.LatencyMs,
		&i.TtftMs,
		&i.UpstreamHttpStatus,
		&i.ErrorCategory,
		&i.RetryCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.UsageSource,
		&i.PricingID,
		&i.EstimatedCostNanoUsd,
		&i.UpstreamRequestID,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const findModelPriceAt = `-- name: FindModelPriceAt :one
SELECT
    id,
    provider,
    model,
    input_nano_usd_per_million,
    output_nano_usd_per_million,
    effective_from,
    effective_to,
    source_note,
    created_at
FROM model_prices
WHERE provider = $1
  AND model = $2
  AND effective_from <= $3
  AND (effective_to IS NULL OR effective_to > $3)
ORDER BY effective_from DESC
LIMIT 1
`

type FindModelPriceAtParams struct {
	Provider string
	Model    string
	AtTime   pgtype.Timestamptz
}

func (q *Queries) FindModelPriceAt(ctx context.Context, arg FindModelPriceAtParams) (ModelPrice, error) {
	row := q.db.QueryRow(ctx, findModelPriceAt, arg.Provider, arg.Model, arg.AtTime)
	var i ModelPrice
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.InputNanoUsdPerMillion,
		&i.OutputNanoUsdPerMillion,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SourceNote,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveProviderCredentialForProjectConfig = `-- name: GetActiveProviderCredentialForProjectConfig :one
SELECT
    configs.project_id,
    configs.provider,
    configs.credential_id,
    configs.base_url_override,
    credentials.secret_ciphertext,
    credentials.secret_nonce,
    credentials.key_version
FROM project_provider_configs AS configs
JOIN provider_credentials AS credentials
  ON credentials.id = configs.credential_id
 AND credentials.project_id = configs.project_id
 AND credentials.provider = configs.provider
WHERE configs.project_id = $1
  AND configs.provider = $2
  AND configs.enabled = true
  AND credentials.status = 'active'
`

type GetActiveProviderCredentialForProjectConfigParams struct {
	ProjectID pgtype.UUID
	Provider  string
}

type GetActiveProviderCredentialForProjectConfigRow struct {
	ProjectID        pgtype.UUID
	Provider         string
	CredentialID     pgtype.UUID
	BaseUrlOverride  pgtype.Text
	SecretCiphertext []byte
	SecretNonce      []byte
	KeyVersion       int16
}

func (q *Queries) GetActiveProviderCredentialForProjectConfig(ctx context.Context, arg GetActiveProviderCredentialForProjectConfigParams) (GetActiveProviderCredentialForProjectConfigRow, error) {
	row := q.db.QueryRow(ctx, getActiveProviderCredentialForProjectConfig, arg.ProjectID, arg.Provider)
	var i GetActiveProviderCredentialForProjectConfigRow
	err := row.Scan(
		&i.ProjectID,
		&i.Provider,
		&i.CredentialID,
		&i.BaseUrlOverride,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.KeyVersion,
	)
	return i, err
}

const getGatewayRequest = `-- name: GetGatewayRequest :one
SELECT
    id,
    project_id,
    virtual_key_id,
    provider_credential_id,
    provider,
    model,
    is_stream,
    status,
    started_at,
    first_chunk_at,
    completed_at,
    latency_ms,
    ttft_ms,
    upstream_http_status,
    error_category,
    retry_count,
    prompt_tokens,
    completion_tokens,
    total_tokens,
    usage_source,
    pricing_id,
    estimated_cost_nano_usd,
    upstream_request_id,
    trace_id,
    created_at
FROM gateway_requests
WHERE id = $1
`

func (q *Queries) GetGatewayRequest(ctx context.Context, id pgtype.UUID) (GatewayRequest, error) {
	row := q.db.QueryRow(ctx, getGatewayRequest, id)
	var i GatewayRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.VirtualKeyID,
		&i.ProviderCredentialID,
		&i.Provider,
		&i.Model,
		&i.IsStream,
		&i.Status,
		&i.StartedAt,
		&i.FirstChunkAt,
		&i.CompletedAt,
		&i.LatencyMs,
		&i.TtftMs,
		&i.UpstreamHttpStatus,
		&i.ErrorCategory,
		&i.RetryCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.UsageSource,
		&i.PricingID,
		&i.EstimatedCostNanoUsd,
		&i.UpstreamRequestID,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}
