// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
	Name        string
	Slug        string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	GithubID    int64
	GithubLogin string
	AvatarUrl   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type VirtualApiKey struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	KeyPrefix  string
	KeyHash    []byte
	Status     string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type WebSession struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}
