// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_provider_configs.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertProjectProviderConfigForOwner = `-- name: UpsertProjectProviderConfigForOwner :one
INSERT INTO project_provider_configs (
    project_id,
    provider,
    credential_id,
    enabled,
    base_url_override,
    updated_at
)
SELECT
    projects.id,
    $1,
    credentials.id,
    $2,
    $3,
    now()
FROM projects
JOIN provider_credentials AS credentials
  ON credentials.id = $4
 AND credentials.project_id = projects.id
 AND credentials.provider = $1
 AND credentials.status = 'active'
WHERE projects.id = $5
  AND projects.owner_user_id = $6
ON CONFLICT (project_id, provider)
DO UPDATE SET
    credential_id = EXCLUDED.credential_id,
    enabled = EXCLUDED.enabled,
    base_url_override = EXCLUDED.base_url_override,
    updated_at = now()
RETURNING
    project_id,
    provider,
    credential_id,
    enabled,
    base_url_override,
    updated_at
`

type UpsertProjectProviderConfigForOwnerParams struct {
	Provider        string
	Enabled         bool
	BaseUrlOverride pgtype.Text
	CredentialID    pgtype.UUID
	ProjectID       pgtype.UUID
	OwnerUserID     pgtype.UUID
}

func (q *Queries) UpsertProjectProviderConfigForOwner(ctx context.Context, arg UpsertProjectProviderConfigForOwnerParams) (ProjectProviderConfig, error) {
	row := q.db.QueryRow(ctx, upsertProjectProviderConfigForOwner,
		arg.Provider,
		arg.Enabled,
		arg.BaseUrlOverride,
		arg.CredentialID,
		arg.ProjectID,
		arg.OwnerUserID,
	)
	var i ProjectProviderConfig
	err := row.Scan(
		&i.ProjectID,
		&i.Provider,
		&i.CredentialID,
		&i.Enabled,
		&i.BaseUrlOverride,
		&i.UpdatedAt,
	)
	return i, err
}
