// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id,
    owner_user_id,
    name,
    slug
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, owner_user_id, name, slug, status, created_at, updated_at
`

type CreateProjectParams struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
	Name        string
	Slug        string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Slug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectForOwner = `-- name: GetProjectForOwner :one
SELECT id, owner_user_id, name, slug, status, created_at, updated_at
FROM projects
WHERE id = $1
  AND owner_user_id = $2
`

type GetProjectForOwnerParams struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
}

func (q *Queries) GetProjectForOwner(ctx context.Context, arg GetProjectForOwnerParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForOwner, arg.ID, arg.OwnerUserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsForOwner = `-- name: ListProjectsForOwner :many
SELECT id, owner_user_id, name, slug, status, created_at, updated_at
FROM projects
WHERE owner_user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProjectsForOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectForOwner = `-- name: UpdateProjectForOwner :one
UPDATE projects
SET
    name = COALESCE($3, name),
    slug = COALESCE($4, slug),
    status = COALESCE($5, status),
    updated_at = now()
WHERE id = $1
  AND owner_user_id = $2
RETURNING id, owner_user_id, name, slug, status, created_at, updated_at
`

type UpdateProjectForOwnerParams struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
	Name        pgtype.Text
	Slug        pgtype.Text
	Status      pgtype.Text
}

func (q *Queries) UpdateProjectForOwner(ctx context.Context, arg UpdateProjectForOwnerParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectForOwner,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Slug,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
