// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_credentials.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderCredentialForOwner = `-- name: CreateProviderCredentialForOwner :one
INSERT INTO provider_credentials (
    id,
    project_id,
    provider,
    label,
    secret_ciphertext,
    secret_nonce,
    key_version
)
SELECT
    $1,
    projects.id,
    $2,
    $3,
    $4,
    $5,
    $6
FROM projects
WHERE projects.id = $7
  AND projects.owner_user_id = $8
RETURNING id, project_id, provider, label, key_version, status, created_at, rotated_at
`

type CreateProviderCredentialForOwnerParams struct {
	ID               pgtype.UUID
	Provider         string
	Label            string
	SecretCiphertext []byte
	SecretNonce      []byte
	KeyVersion       int16
	ProjectID        pgtype.UUID
	OwnerUserID      pgtype.UUID
}

type CreateProviderCredentialForOwnerRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Provider   string
	Label      string
	KeyVersion int16
	Status     string
	CreatedAt  pgtype.Timestamptz
	RotatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateProviderCredentialForOwner(ctx context.Context, arg CreateProviderCredentialForOwnerParams) (CreateProviderCredentialForOwnerRow, error) {
	row := q.db.QueryRow(ctx, createProviderCredentialForOwner,
		arg.ID,
		arg.Provider,
		arg.Label,
		arg.SecretCiphertext,
		arg.SecretNonce,
		arg.KeyVersion,
		arg.ProjectID,
		arg.OwnerUserID,
	)
	var i CreateProviderCredentialForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.Label,
		&i.KeyVersion,
		&i.Status,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const disableProviderCredentialForOwner = `-- name: DisableProviderCredentialForOwner :one
UPDATE provider_credentials AS credentials
SET status = CASE
    WHEN credentials.status = 'active' THEN 'disabled'
    ELSE credentials.status
END
FROM projects
WHERE credentials.id = $1
  AND credentials.project_id = $2
  AND projects.id = credentials.project_id
  AND projects.owner_user_id = $3
RETURNING credentials.id, credentials.project_id, credentials.provider, credentials.label, credentials.key_version, credentials.status, credentials.created_at, credentials.rotated_at
`

type DisableProviderCredentialForOwnerParams struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	OwnerUserID pgtype.UUID
}

type DisableProviderCredentialForOwnerRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Provider   string
	Label      string
	KeyVersion int16
	Status     string
	CreatedAt  pgtype.Timestamptz
	RotatedAt  pgtype.Timestamptz
}

func (q *Queries) DisableProviderCredentialForOwner(ctx context.Context, arg DisableProviderCredentialForOwnerParams) (DisableProviderCredentialForOwnerRow, error) {
	row := q.db.QueryRow(ctx, disableProviderCredentialForOwner, arg.ID, arg.ProjectID, arg.OwnerUserID)
	var i DisableProviderCredentialForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.Label,
		&i.KeyVersion,
		&i.Status,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const listProviderCredentialsForOwner = `-- name: ListProviderCredentialsForOwner :many
SELECT
    credentials.id,
    credentials.project_id,
    credentials.provider,
    credentials.label,
    credentials.key_version,
    credentials.status,
    credentials.created_at,
    credentials.rotated_at
FROM provider_credentials AS credentials
JOIN projects ON projects.id = credentials.project_id
WHERE credentials.project_id = $1
  AND projects.owner_user_id = $2
ORDER BY credentials.created_at DESC, credentials.id DESC
`

type ListProviderCredentialsForOwnerParams struct {
	ProjectID   pgtype.UUID
	OwnerUserID pgtype.UUID
}

type ListProviderCredentialsForOwnerRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Provider   string
	Label      string
	KeyVersion int16
	Status     string
	CreatedAt  pgtype.Timestamptz
	RotatedAt  pgtype.Timestamptz
}

func (q *Queries) ListProviderCredentialsForOwner(ctx context.Context, arg ListProviderCredentialsForOwnerParams) ([]ListProviderCredentialsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listProviderCredentialsForOwner, arg.ProjectID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderCredentialsForOwnerRow{}
	for rows.Next() {
		var i ListProviderCredentialsForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Provider,
			&i.Label,
			&i.KeyVersion,
			&i.Status,
			&i.CreatedAt,
			&i.RotatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateProviderCredentialForOwner = `-- name: RotateProviderCredentialForOwner :one
UPDATE provider_credentials AS credentials
SET
    secret_ciphertext = $4,
    secret_nonce = $5,
    key_version = $6,
    rotated_at = now()
FROM projects
WHERE credentials.id = $1
  AND credentials.project_id = $2
  AND projects.id = credentials.project_id
  AND projects.owner_user_id = $3
RETURNING credentials.id, credentials.project_id, credentials.provider, credentials.label, credentials.key_version, credentials.status, credentials.created_at, credentials.rotated_at
`

type RotateProviderCredentialForOwnerParams struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	OwnerUserID      pgtype.UUID
	SecretCiphertext []byte
	SecretNonce      []byte
	KeyVersion       int16
}

type RotateProviderCredentialForOwnerRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Provider   string
	Label      string
	KeyVersion int16
	Status     string
	CreatedAt  pgtype.Timestamptz
	RotatedAt  pgtype.Timestamptz
}

func (q *Queries) RotateProviderCredentialForOwner(ctx context.Context, arg RotateProviderCredentialForOwnerParams) (RotateProviderCredentialForOwnerRow, error) {
	row := q.db.QueryRow(ctx, rotateProviderCredentialForOwner,
		arg.ID,
		arg.ProjectID,
		arg.OwnerUserID,
		arg.SecretCiphertext,
		arg.SecretNonce,
		arg.KeyVersion,
	)
	var i RotateProviderCredentialForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.Label,
		&i.KeyVersion,
		&i.Status,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}
