// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByGitHubID = `-- name: GetUserByGitHubID :one
SELECT id, github_id, github_login, avatar_url, created_at, updated_at
FROM users
WHERE github_id = $1
`

func (q *Queries) GetUserByGitHubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGitHubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubLogin,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, github_login, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubLogin,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserFromGitHub = `-- name: UpsertUserFromGitHub :one
INSERT INTO users (
    id,
    github_id,
    github_login,
    avatar_url
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (github_id) DO UPDATE SET
    github_login = EXCLUDED.github_login,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = now()
RETURNING id, github_id, github_login, avatar_url, created_at, updated_at
`

type UpsertUserFromGitHubParams struct {
	ID          pgtype.UUID
	GithubID    int64
	GithubLogin string
	AvatarUrl   pgtype.Text
}

func (q *Queries) UpsertUserFromGitHub(ctx context.Context, arg UpsertUserFromGitHubParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserFromGitHub,
		arg.ID,
		arg.GithubID,
		arg.GithubLogin,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubLogin,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
