// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: virtual_api_keys.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVirtualAPIKeyForOwner = `-- name: CreateVirtualAPIKeyForOwner :one
INSERT INTO virtual_api_keys (
    id,
    project_id,
    name,
    key_prefix,
    key_hash
)
SELECT
    $1,
    projects.id,
    $2,
    $3,
    $4
FROM projects
WHERE projects.id = $5
  AND projects.owner_user_id = $6
RETURNING id, project_id, name, key_prefix, status, created_at, last_used_at, revoked_at
`

type CreateVirtualAPIKeyForOwnerParams struct {
	ID          pgtype.UUID
	Name        string
	KeyPrefix   string
	KeyHash     []byte
	ProjectID   pgtype.UUID
	OwnerUserID pgtype.UUID
}

type CreateVirtualAPIKeyForOwnerRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	KeyPrefix  string
	Status     string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) CreateVirtualAPIKeyForOwner(ctx context.Context, arg CreateVirtualAPIKeyForOwnerParams) (CreateVirtualAPIKeyForOwnerRow, error) {
	row := q.db.QueryRow(ctx, createVirtualAPIKeyForOwner,
		arg.ID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.ProjectID,
		arg.OwnerUserID,
	)
	var i CreateVirtualAPIKeyForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyPrefix,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const disableVirtualAPIKeyForOwner = `-- name: DisableVirtualAPIKeyForOwner :one
UPDATE virtual_api_keys AS keys
SET status = CASE
    WHEN keys.status = 'active' THEN 'disabled'
    ELSE keys.status
END
FROM projects
WHERE keys.id = $1
  AND keys.project_id = $2
  AND projects.id = keys.project_id
  AND projects.owner_user_id = $3
RETURNING keys.id, keys.project_id, keys.name, keys.key_prefix, keys.status, keys.created_at, keys.last_used_at, keys.revoked_at
`

type DisableVirtualAPIKeyForOwnerParams struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	OwnerUserID pgtype.UUID
}

type DisableVirtualAPIKeyForOwnerRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	KeyPrefix  string
	Status     string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) DisableVirtualAPIKeyForOwner(ctx context.Context, arg DisableVirtualAPIKeyForOwnerParams) (DisableVirtualAPIKeyForOwnerRow, error) {
	row := q.db.QueryRow(ctx, disableVirtualAPIKeyForOwner, arg.ID, arg.ProjectID, arg.OwnerUserID)
	var i DisableVirtualAPIKeyForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyPrefix,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listVirtualAPIKeysForOwner = `-- name: ListVirtualAPIKeysForOwner :many
SELECT
    keys.id,
    keys.project_id,
    keys.name,
    keys.key_prefix,
    keys.status,
    keys.created_at,
    keys.last_used_at,
    keys.revoked_at
FROM virtual_api_keys AS keys
JOIN projects ON projects.id = keys.project_id
WHERE keys.project_id = $1
  AND projects.owner_user_id = $2
ORDER BY keys.created_at DESC, keys.id DESC
`

type ListVirtualAPIKeysForOwnerParams struct {
	ProjectID   pgtype.UUID
	OwnerUserID pgtype.UUID
}

type ListVirtualAPIKeysForOwnerRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	KeyPrefix  string
	Status     string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) ListVirtualAPIKeysForOwner(ctx context.Context, arg ListVirtualAPIKeysForOwnerParams) ([]ListVirtualAPIKeysForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listVirtualAPIKeysForOwner, arg.ProjectID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVirtualAPIKeysForOwnerRow{}
	for rows.Next() {
		var i ListVirtualAPIKeysForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.KeyPrefix,
			&i.Status,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeVirtualAPIKeyForOwner = `-- name: RevokeVirtualAPIKeyForOwner :one
UPDATE virtual_api_keys AS keys
SET
    status = 'revoked',
    revoked_at = COALESCE(keys.revoked_at, now())
FROM projects
WHERE keys.id = $1
  AND keys.project_id = $2
  AND projects.id = keys.project_id
  AND projects.owner_user_id = $3
RETURNING keys.id, keys.project_id, keys.name, keys.key_prefix, keys.status, keys.created_at, keys.last_used_at, keys.revoked_at
`

type RevokeVirtualAPIKeyForOwnerParams struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	OwnerUserID pgtype.UUID
}

type RevokeVirtualAPIKeyForOwnerRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	KeyPrefix  string
	Status     string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) RevokeVirtualAPIKeyForOwner(ctx context.Context, arg RevokeVirtualAPIKeyForOwnerParams) (RevokeVirtualAPIKeyForOwnerRow, error) {
	row := q.db.QueryRow(ctx, revokeVirtualAPIKeyForOwner, arg.ID, arg.ProjectID, arg.OwnerUserID)
	var i RevokeVirtualAPIKeyForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyPrefix,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}
