// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: web_sessions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebSession = `-- name: CreateWebSession :exec
INSERT INTO web_sessions (
    id,
    user_id,
    token_hash,
    expires_at,
    created_at,
    last_seen_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $5
)
`

type CreateWebSessionParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateWebSession(ctx context.Context, arg CreateWebSessionParams) error {
	_, err := q.db.Exec(ctx, createWebSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteWebSessionByTokenHash = `-- name: DeleteWebSessionByTokenHash :exec
DELETE FROM web_sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteWebSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteWebSessionByTokenHash, tokenHash)
	return err
}

const getValidWebSessionByTokenHash = `-- name: GetValidWebSessionByTokenHash :one
SELECT
    users.id AS user_id,
    users.github_id,
    users.github_login,
    users.avatar_url,
    web_sessions.expires_at
FROM web_sessions
JOIN users ON users.id = web_sessions.user_id
WHERE web_sessions.token_hash = $1
  AND web_sessions.expires_at > $2
`

type GetValidWebSessionByTokenHashParams struct {
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

type GetValidWebSessionByTokenHashRow struct {
	UserID      pgtype.UUID
	GithubID    int64
	GithubLogin string
	AvatarUrl   pgtype.Text
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) GetValidWebSessionByTokenHash(ctx context.Context, arg GetValidWebSessionByTokenHashParams) (GetValidWebSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getValidWebSessionByTokenHash, arg.TokenHash, arg.ExpiresAt)
	var i GetValidWebSessionByTokenHashRow
	err := row.Scan(
		&i.UserID,
		&i.GithubID,
		&i.GithubLogin,
		&i.AvatarUrl,
		&i.ExpiresAt,
	)
	return i, err
}
